import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./style.css";
import NavBar from "@/components/navbar/NavBar";
import Links from "@/components/navbar/Links";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <meta charSet="utf-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
    </head>
    <body className={inter.className}>
    {children}
    </body>
    </html>
  );
}
